### ISSUE TITLE
Yang module / grouping uni-information-group (from Janne's review)

### ISSUE THREAD

**Issue by oscargdd** [oscargdd/uni-topology#3]
•	4. Yang module / grouping uni-information-group
Please consider adding a "name" attribute for APs, in addition to attachment-id (which id defined to be of type ietf-network-topology:tp-id). Reason: RFC 8345 defines tp-id to be URI, with implementation-defined structure, meaning it's primarily for machine-to-machine use. There is a clear need for a human-readable name for interfaces, especially in the case of service access points.

**Comment by sbarguil** [comment]
augment /nw:networks/nw:network/nw:node:
    +--rw service-attachment-points
       +--rw service-attachment-point* [attachment-id]
          +--rw attachment-id         nt:tp-id
          +--rw name?                 string
          +--ro type?                 identityref
          +--rw admin-status?         boolean
          +--rw oper-status?          boolean
          +--rw encapsulation-type?   identityref
